import { ProviderInfo } from '../types/provider';

export const SEED_PROVIDERS: ProviderInfo[] = [
  {
    id: 'redtube',
    name: 'RedTube',
    category: 'tube',
    baseUrl: 'https://www.redtube.com',
    icon: '🔴',
    enabled: true,
    priority: 95,
    quality: 'high',
    description: 'Premier free tube site with fast streaming and official public REST API.',
    tags: ['tube', 'hd', 'amateur', 'popular', 'verified'],
    hasApi: true,
    sourceCategory: 'Free Tube Sites',
    lastVerified: new Date().toISOString(),
  },
  {
    id: 'eporner',
    name: 'EPORNER',
    category: 'tube',
    baseUrl: 'https://www.eporner.com',
    icon: '⚡',
    enabled: true,
    priority: 98,
    quality: 'high',
    description: 'Crystal-clear 1080p and 4K video streams with official JSON API and embed player.',
    tags: ['4k', '1080p', 'fast', 'hd', 'tube'],
    hasApi: true,
    sourceCategory: 'Free Tube Sites',
    lastVerified: new Date().toISOString(),
  },
  {
    id: 'rule34',
    name: 'Rule34',
    category: 'anime',
    baseUrl: 'https://rule34.xxx',
    icon: '🎨',
    enabled: true,
    priority: 92,
    quality: 'high',
    description: 'Massive booru community featuring animations, hentai, GIFs, and illustrations with public API.',
    tags: ['anime', 'hentai', 'booru', 'animated', 'art', 'gif'],
    hasApi: true,
    sourceCategory: 'Free Hentai & Anime Sites',
    lastVerified: new Date().toISOString(),
  },
  {
    id: 'gelbooru',
    name: 'Gelbooru',
    category: 'anime',
    baseUrl: 'https://gelbooru.com',
    icon: '🌸',
    enabled: true,
    priority: 88,
    quality: 'high',
    description: 'Premier anime/manga image & video board with fast metadata JSON endpoints.',
    tags: ['anime', 'art', 'booru', 'illustration', 'video'],
    hasApi: true,
    sourceCategory: 'Free Hentai & Anime Sites',
    lastVerified: new Date().toISOString(),
  },
  {
    id: 'danbooru',
    name: 'Danbooru',
    category: 'image',
    baseUrl: 'https://danbooru.donmai.us',
    icon: '🖼️',
    enabled: true,
    priority: 85,
    quality: 'high',
    description: 'High quality tagged anime art repository with extensive search and REST endpoints.',
    tags: ['image', 'art', 'tags', 'anime'],
    hasApi: true,
    sourceCategory: 'Free Image Sites',
    lastVerified: new Date().toISOString(),
  },
  {
    id: 'spankbang',
    name: 'SpankBang',
    category: 'tube',
    baseUrl: 'https://spankbang.com',
    icon: '💥',
    enabled: true,
    priority: 90,
    quality: 'high',
    description: 'Modern clean tube with quick previews, trending feeds, and responsive embeds.',
    tags: ['tube', '4k', 'trending', 'short-clips'],
    hasApi: false,
    sourceCategory: 'Free Tube Sites',
    lastVerified: new Date().toISOString(),
  },
  {
    id: 'xvideos',
    name: 'XVideos',
    category: 'tube',
    baseUrl: 'https://www.xvideos.com',
    icon: '❌',
    enabled: true,
    priority: 94,
    quality: 'high',
    description: 'World largest collection of free community and studio adult clips.',
    tags: ['popular', 'tube', 'variety', 'global'],
    hasApi: false,
    sourceCategory: 'Free Tube Sites',
    lastVerified: new Date().toISOString(),
  },
  {
    id: 'xnxx',
    name: 'XNXX',
    category: 'tube',
    baseUrl: 'https://www.xnxx.com',
    icon: '✖️',
    enabled: true,
    priority: 89,
    quality: 'high',
    description: 'Classic high-volume tube with millions of indexed videos and quick embeds.',
    tags: ['tube', 'classic', 'amateur', 'free'],
    hasApi: false,
    sourceCategory: 'Free Tube Sites',
    lastVerified: new Date().toISOString(),
  },
  {
    id: 'redgifs',
    name: 'RedGIFs',
    category: 'gif',
    baseUrl: 'https://www.redgifs.com',
    icon: '🎞️',
    enabled: true,
    priority: 96,
    quality: 'high',
    description: 'High-definition short looping videos and GIFs, ideal for vertical feed & TikTok view.',
    tags: ['gif', 'short-clips', 'tiktok', 'loop', 'sound'],
    hasApi: true,
    sourceCategory: 'Free GIF Sites',
    lastVerified: new Date().toISOString(),
  },
  {
    id: 'hentaimama',
    name: 'HentaiMama',
    category: 'anime',
    baseUrl: 'https://hentaimama.io',
    icon: '🍙',
    enabled: true,
    priority: 84,
    quality: 'medium',
    description: 'Subbed & uncensored anime series and high quality animation streams.',
    tags: ['anime', 'hentai', 'episodes', 'series', 'uncensored'],
    hasApi: false,
    sourceCategory: 'Free Hentai & Anime Sites',
    lastVerified: new Date().toISOString(),
  },
  {
    id: 'pornhub_free',
    name: 'Pornhub (Public)',
    category: 'tube',
    baseUrl: 'https://www.pornhub.com',
    icon: '⬛',
    enabled: true,
    priority: 93,
    quality: 'high',
    description: 'Public free tube videos with embedded players and rich tag metadata.',
    tags: ['tube', 'verified', '4k', 'trending'],
    hasApi: false,
    sourceCategory: 'Free Tube Sites',
    lastVerified: new Date().toISOString(),
  },
  {
    id: 'gifdelivery',
    name: 'GIFDeliveryNetwork',
    category: 'gif',
    baseUrl: 'https://www.redgifs.com',
    icon: '⚡',
    enabled: true,
    priority: 82,
    quality: 'high',
    description: 'Optimized short format video CDN for rapid mobile scrolling.',
    tags: ['gif', 'loop', 'mobile', 'short'],
    hasApi: true,
    sourceCategory: 'Free GIF Sites',
    lastVerified: new Date().toISOString(),
  },
];
